/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsModelsProvidersRouteImport } from './routes/settings/models-providers'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAiOptionsRouteImport } from './routes/settings/ai-options'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as ChatThreadThreadIdRouteImport } from './routes/_chat.thread.$threadId'
import { Route as ChatSSharedThreadIdRouteImport } from './routes/_chat.s.$sharedThreadId'
import { ServerRoute as ApiPhrSplatServerRouteImport } from './routes/api/phr/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsModelsProvidersRoute = SettingsModelsProvidersRouteImport.update({
  id: '/models-providers',
  path: '/models-providers',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAiOptionsRoute = SettingsAiOptionsRouteImport.update({
  id: '/ai-options',
  path: '/ai-options',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadThreadIdRoute = ChatThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSSharedThreadIdRoute = ChatSSharedThreadIdRouteImport.update({
  id: '/s/$sharedThreadId',
  path: '/s/$sharedThreadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiPhrSplatServerRoute = ApiPhrSplatServerRouteImport.update({
  id: '/api/phr/$',
  path: '/api/phr/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/settings/ai-options': typeof SettingsAiOptionsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/models-providers': typeof SettingsModelsProvidersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/': typeof ChatIndexRoute
  '/s/$sharedThreadId': typeof ChatSSharedThreadIdRoute
  '/thread/$threadId': typeof ChatThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/settings/ai-options': typeof SettingsAiOptionsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/models-providers': typeof SettingsModelsProvidersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/': typeof ChatIndexRoute
  '/s/$sharedThreadId': typeof ChatSSharedThreadIdRoute
  '/thread/$threadId': typeof ChatThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_chat': typeof ChatRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/settings/ai-options': typeof SettingsAiOptionsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/models-providers': typeof SettingsModelsProvidersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/s/$sharedThreadId': typeof ChatSSharedThreadIdRoute
  '/_chat/thread/$threadId': typeof ChatThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/privacy-policy'
    | '/auth/$pathname'
    | '/settings/ai-options'
    | '/settings/appearance'
    | '/settings/attachments'
    | '/settings/models-providers'
    | '/settings/profile'
    | '/settings/usage'
    | '/'
    | '/s/$sharedThreadId'
    | '/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/privacy-policy'
    | '/auth/$pathname'
    | '/settings/ai-options'
    | '/settings/appearance'
    | '/settings/attachments'
    | '/settings/models-providers'
    | '/settings/profile'
    | '/settings/usage'
    | '/'
    | '/s/$sharedThreadId'
    | '/thread/$threadId'
  id:
    | '__root__'
    | '/settings'
    | '/_chat'
    | '/privacy-policy'
    | '/auth/$pathname'
    | '/settings/ai-options'
    | '/settings/appearance'
    | '/settings/attachments'
    | '/settings/models-providers'
    | '/settings/profile'
    | '/settings/usage'
    | '/_chat/'
    | '/_chat/s/$sharedThreadId'
    | '/_chat/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/phr/$': typeof ApiPhrSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/phr/$': typeof ApiPhrSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/phr/$': typeof ApiPhrSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/phr/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/phr/$'
  id: '__root__' | '/api/auth/$' | '/api/phr/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiPhrSplatServerRoute: typeof ApiPhrSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/models-providers': {
      id: '/settings/models-providers'
      path: '/models-providers'
      fullPath: '/settings/models-providers'
      preLoaderRoute: typeof SettingsModelsProvidersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/ai-options': {
      id: '/settings/ai-options'
      path: '/ai-options'
      fullPath: '/settings/ai-options'
      preLoaderRoute: typeof SettingsAiOptionsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/thread/$threadId': {
      id: '/_chat/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ChatThreadThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/s/$sharedThreadId': {
      id: '/_chat/s/$sharedThreadId'
      path: '/s/$sharedThreadId'
      fullPath: '/s/$sharedThreadId'
      preLoaderRoute: typeof ChatSSharedThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/phr/$': {
      id: '/api/phr/$'
      path: '/api/phr/$'
      fullPath: '/api/phr/$'
      preLoaderRoute: typeof ApiPhrSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAiOptionsRoute: typeof SettingsAiOptionsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsModelsProvidersRoute: typeof SettingsModelsProvidersRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAiOptionsRoute: SettingsAiOptionsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsModelsProvidersRoute: SettingsModelsProvidersRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsUsageRoute: SettingsUsageRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatSSharedThreadIdRoute: typeof ChatSSharedThreadIdRoute
  ChatThreadThreadIdRoute: typeof ChatThreadThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatSSharedThreadIdRoute: ChatSSharedThreadIdRoute,
  ChatThreadThreadIdRoute: ChatThreadThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiPhrSplatServerRoute: ApiPhrSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
